#Config
#Wed Dec 15 14:27:38 ART 2021
Appserver.url=AppServer\://host\:port/service
server.port=43551
Appserver.modo=1
Appserver.maxthreads=25
server.error.include-message=always
Appserver.name=
certificado=C\:/Progress/OpenEdge/certs/archive/psccerts.jar
